name: Python Unit Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r padel_7_booking_bot/requirements.txt
          pip install pytest

      - name: Run Pytest in padel_7_booking_bot
        run: pytest
        working-directory: padel_7_booking_bot
