name: Python Unit Tests

on:
  push:
    branches:
      - '**'
      - '!main'


jobs:
  check-code-changes:
    name: Check Code Changes
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_files.outputs.skip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if tests should run
        id: check_files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^padel_7_booking_bot/' || true)
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No source code changes, skipping tests."
            echo "skip=true" >> $GITHUB_ENV
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_ENV
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: check-code-changes
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      # This step marks the workflow as successful when tests are skipped
      - name: Mark Tests as Successful if Skipped
        if: needs.check-code-changes.outputs.skip == 'true'
        run: |
          echo "No source code changes. Marking tests as successful."
          exit 0  # Ensure job succeeds

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/padel7_booking_bot" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./padel7_booking_bot/requirements.txt
          pip install -r ./padel7_booking_bot/requirements-test.txt

      - name: Run Pytest in padel7_booking_bot
        run: pytest --ignore=tests/integration
        working-directory: padel7_booking_bot
